setup.ilm.enabled: false
setup.template.enabled: true
setup.template.name: "nginx-log"
setup.template.pattern: "nginx-log-*"
setup.template.overwrite: true
setup.template.append_fields:
- name: content
  type: text

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log

output.elasticsearch:
  hosts: ["http://172.17.0.3:5080"]
  timeout: 10
  path: "/api/default/"
  index: "nginx-log-%{+yyyy.MM.dd}"
  username: "root@example.com"
  password: "Complexpass#123"
